import type { Metadata } from "next";
import localfont from "next/font/local";
import store from "@/redux/store";
import ReduxProvider from "@/redux/provider";
import "./globals.css";

const comic = localfont({
  src: "../public/fonts/ComicSansMS3.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={comic.className}
        style={{ height: "100vh", width: "100vw" }}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
